// <auto-generated />
namespace booksmanagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DrawingFileRefAddedInCarPartr : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DrawingFileRefAddedInCarPartr));
        
        string IMigrationMetadata.Id
        {
            get { return "202011102104416_DrawingFileRefAddedInCarPartr"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
